# Generated by Django 3.2.3 on 2021-05-27 06:12

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('PDF_tranformador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to=pathlib.PureWindowsPath('C:/Users/preya/OneDrive/Desktop/INGENIERIA DE SOFTWARE/Proyecto/PDF_Reader/media')),
        ),
    ]
