# Generated by Django 3.2.3 on 2021-05-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDF_tranformador', '0002_alter_archivo_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='Titulo',
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to='Pdf'),
        ),
    ]
